"""ugv_controller_constants.py"""
UGV_IP = "192.168.1.4"
UGV_DEFAULT_SPEED = 50
FORWARD = "w"
BACKWARD = "s"
LEFT = "d"
RIGHT = "a"
STOP = "x"
HLROBOTICS_TITLE = "************* HLRobotics and Software Automation ************* \n "
UGV_CONTROL_SYSTEM_TITLE = "UGV CONTROL SYSTEM"
