"""ugv_controller_constatnts.py"""
UGV_IP = "192.168.1.9"
UGV_DEFAULT_SPEED = 80
FORWARD = "w"
BACKWARD = "s"
LEFT = "d"
RIGHT = "r"
STOP = "x"
HLROBOTICS_TITLE = "************* HLRobotics and Software Automation ************* \n "
UGV_CONTROL_SYSTEM_TITLE = "UGV CONTROL SYSTEM"
